version: '3.5'

services:

  react:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './application:/usr/src/app'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development

